/**:
  ros__parameters:
    log_dir: /home/yuchen/ASRL/temp/steam_icp/aeva_long/steam
    output_dir: /home/yuchen/ASRL/temp/steam_icp/aeva_long/steam

    # VISUALIZATION OPTIONS ----
    visualization_options:
      odometry: false
      raw_points: false
      sampled_points: false
      map_points: false
      T_sr_vec: [-0.835, -0.39, 0.103, 0.0, 0.0, 0.0]

    # DATASET OPTIONS ----
    dataset: AEVA_long
    dataset_options:
      all_sequences: true
      root_path: /home/yuchen/ASRL/data/aeva
      sequence: "04"
      init_frame: 0 # 5675 (highway 7 front image)
      last_frame: 100000 # 5680 (highway 7 front image)
      min_dist_lidar_center: 5.0
      max_dist_lidar_center: 100.0

    # ODOMETRY OPTIONS ----
    odometry: STEAM
    odometry_options:
      debug_print: true
      debug_path: /home/yuchen/ASRL/temp/steam_icp/aeva_long/steam

      elastic:
        num_threads: 20

      steam:
        T_sr_vec: [-0.835, -0.39, 0.103, 0.0, 0.0, 0.0]
        qc_diag: [50.0, 50.0, 50.0, 5.0, 5.0, 5.0]
        use_rv: false
        num_threads: 20
