/**:
  ros__parameters:
    log_dir: /home/yuchen/ASRL/temp/steam_icp/boreas/aeva/elastic
    output_dir: /home/yuchen/ASRL/temp/steam_icp/boreas/aeva/elastic

    # VISUALIZATION OPTIONS ----
    visualization_options:
      odometry: false
      raw_points: false
      sampled_points: false
      map_points: false
      T_sr_vec: [-0.835, -0.39, 0.103, 0.0, 0.0, 0.0]

    # DATASET OPTIONS ----
    dataset: AEVA
    dataset_options:
      all_sequences: true
      root_path: /home/yuchen/ASRL/data/boreas/sequences
      sequence: "boreas-2022-08-05-13-30"
      init_frame: 0
      last_frame: 100000
      min_dist_lidar_center: 5.0
      max_dist_lidar_center: 100.0

    # ODOMETRY OPTIONS ----
    odometry: Elastic
    odometry_options:
      debug_print: true
      debug_path: /home/yuchen/ASRL/temp/steam_icp/boreas/aeva/elastic

      elastic:
        num_threads: 10
