/**:
  ros__parameters:
    log_dir: /home/ywu/ASRL/temp/steam_icp/aeva/steam
    output_dir: /home/ywu/ASRL/temp/steam_icp/aeva/steam

    # VISUALIZATION OPTIONS ----
    visualization_options:
      odometry: false
      raw_points: false
      sampled_points: false
      map_points: false
      T_sr_vec: [-1.42, -0.24, -1.37, 0.0, 0.0, 0.0]

    # DATASET OPTIONS ----
    dataset: Aeva
    dataset_options:
      all_sequences: true
      root_path: /home/ywu/ASRL/steam_icp/data/aeva
      sequence: "00" # 02 (Robin Williams Tunnel)
      init_frame: 0 # 50 (tunnel start)
      last_frame: 100000 # 230 (tunnel end)
      min_dist_lidar_center: 5.0
      max_dist_lidar_center: 100.0

    # ODOMETRY OPTIONS ----
    odometry: STEAM
    odometry_options:
      debug_print: true
      debug_path: /home/ywu/ASRL/temp/steam_icp/aeva/steam

      elastic:
        num_threads: 20

      steam:
        T_sr_vec: [-1.42, -0.24, -1.37, 0.0, 0.0, 0.0]
        qc_diag: [50.0, 50.0, 50.0, 5.0, 5.0, 5.0]
        use_rv: false
        num_threads: 20
