/**:
  ros__parameters:
    log_dir: /home/krb/ASRL/temp/steam_icp/boreas_velodyne/steamlio
    output_dir: /home/krb/ASRL/temp/steam_icp/boreas_velodyne/steamlio

    # VISUALIZATION OPTIONS ----
    visualization_options:
      odometry: true
      raw_points: false
      sampled_points: true
      map_points: false

    # DATASET OPTIONS ----
    dataset: BoreasVelodyne
    dataset_options:
      all_sequences: false
      root_path: /workspace/raid/krb/boreas
      sequence: "boreas-2021-09-02-11-42"
      init_frame: 0 # 5675 (highway 7 front image)
      last_frame: 100000 # 5680 (highway 7 front image)
      min_dist_sensor_center: 5.0
      max_dist_sensor_center: 100.0

    # ODOMETRY OPTIONS ----
    odometry: STEAMLIO
    odometry_options:
      debug_print: true
      debug_path: /home/krb/ASRL/temp/steam_icp/boreas_velodyne/steamlio
      num_iters_icp: 10

      elastic:
        num_threads: 20

      steam:
        # Note: we train the parameters in the applanix frame but these are in the robot frame...
        # So, swap x-y and roll-pitch for both qc and ad given the values from the Jupyter notebook.
        # 7e7 seems too high.
        # qc_diag: [7.446e+04, 7.446e+04,  2.699e+03,  7.155e+01,  1.183e+01,  6.578e-01]
        # ad_diag: [4.909e+00, 7.293e+00,  9.998e+00,  8.210e+00,  1.670e+00,  5.980e+00]
        qc_diag: [6.18047567e+04, 6.18047567e+04, 3.40402641e+03, 6.13821100e+01, 6.13821100e+01, 9.85316597e+03]
        # ad_diag: [100.11439693, 100.11512779, 100.08909343, 100.07804446, 100.07103628, 100.11791258]
        ad_diag: [10.0, 10.0, 10.0, 100.07804446, 100.07103628, 100.11791258]

        # qc_diag: [50.0,50.0,50.0,5.0,5.0,5.0]
        # ad_diag: [0.0,0.0,0.0,10.0,10.0,10.0]
        num_threads: 20
        gravity: -9.8042  #-9.8042
        r_imu_acc: [0.43000461, 0.33698219, 0.29589244]
        r_imu_ang: [0.04898588, 0.06860401, 0.04319808]
        # r_imu_acc: [0.03418968, 0.01292128, 0.00767178]
        # r_imu_ang: [5.75866815e-06, 2.21540004e-05, 3.48544315e-06]
        p0_imu: 0.01
        q_imu: 0.01
        use_imu: true
        max_iterations: 5
        verbose: false
        delay_adding_points: 1
        qg_diag: [1.0e-6, 1.0e-6, 1.0e-6, 1.0e-6, 1.0e-6, 1.0e-6]
        T_mi_init_only: true