/**:
  ros__parameters:
    log_dir: /home/krb/ASRL/temp/steam_icp/boreas_velodyne/steamlio
    output_dir: /home/krb/ASRL/temp/steam_icp/boreas_velodyne/steamlio

    # VISUALIZATION OPTIONS ----
    visualization_options:
      odometry: true
      raw_points: false
      sampled_points: true
      map_points: true

    # DATASET OPTIONS ----
    dataset: BoreasVelodyne
    dataset_options:
      all_sequences: false
      root_path: /workspace/raid/krb/boreas
      sequence: "boreas-2021-09-02-11-42"
      init_frame: 0 # 5675 (highway 7 front image)
      last_frame: 100000 # 5680 (highway 7 front image)
      min_dist_sensor_center: 5.0
      max_dist_sensor_center: 100.0

    # ODOMETRY OPTIONS ----
    odometry: STEAMLIO
    odometry_options:
      debug_print: true
      debug_path: /home/krb/ASRL/temp/steam_icp/boreas_velodyne/steamlio
      # num_iters_icp: 100

      elastic:
        num_threads: 20

      steam:
        qc_diag: [1.0e-1, 1.0e-1, 1.0e-1, 1.0e-1, 1.0e-1, 1.0e-1]
        num_threads: 20
        gravity: -9.8042 #-9.8042
        r_imu_acc: 0.1
        r_imu_ang: 0.1
        p0_imu: 0.1
        q_imu: 0.0001
        max_iterations: 5
        verbose: false
        delay_adding_points: 1
        qg_diag: [1.0e-3, 1.0e-3, 1.0e-3, 1.0e-1, 1.0e-1, 1.0e-1]