/**:
  ros__parameters:
    log_dir: /home/ywu/ASRL/temp/steam_icp/boreas_aeva/steam
    output_dir: /home/ywu/ASRL/temp/steam_icp/boreas_aeva/steam

    # VISUALIZATION OPTIONS ----
    visualization_options:
      odometry: false
      raw_points: false
      sampled_points: false
      map_points: false
      T_sr_vec: [-0.835, -0.39, 0.103, 0.0, 0.0, 0.0]

    # DATASET OPTIONS ----
    dataset: BoreasNavtech
    dataset_options:
      all_sequences: true
      root_path: /home/ywu/ASRL/steam_icp/data/boreas_aeva
      sequence: "04"
      init_frame: 0 # 5675 (highway 7 front image)
      last_frame: 100000 # 5680 (highway 7 front image)
      min_dist_sensor_center: 2.0
      max_dist_sensor_center: 80.0
      radar_resolution: 0.0596
      radar_range_offset: -0.31
      modified_cacfar_width: 101
      modified_cacfar_guard: 5
      modified_cacfar_threshold: 1.0
      modified_cacfar_threshold2: 0.0
      modified_cacfar_threshold3: 0.09

    # ODOMETRY OPTIONS ----
    odometry: STEAM
    odometry_options:
      debug_print: true
      debug_path: /home/ywu/ASRL/temp/steam_icp/boreas_aeva/steam

      elastic:
        num_threads: 20

      steam:
        T_sr_vec: [-0.835, -0.39, 0.103, 0.0, 0.0, 0.0]
        qc_diag: [50.0, 50.0, 50.0, 5.0, 5.0, 5.0]
        use_rv: false
        num_threads: 20
