/**:
  ros__parameters:
    log_dir: /home/asrl/ASRL/temp/steam_icp/boreas_velodyne/steamlo
    output_dir: /home/asrl/ASRL/temp/steam_icp/boreas_velodyne/steamlo
    eval_only: false

    # VISUALIZATION OPTIONS ----
    visualization_options:
      odometry: true
      raw_points: false
      sampled_points: true
      map_points: false

    # DATASET OPTIONS ----
    dataset: BoreasVelodyne
    dataset_options:
      all_sequences: true
      root_path: /home/asrl/boreas_docker_local
      sequence: "boreas-2021-09-09-15-28" #"boreas-2021-09-02-11-42"
      init_frame: 0 # 5675 (highway 7 front image)
      last_frame: 100000 # 5680 (highway 7 front image)
      min_dist_sensor_center: 5.0
      max_dist_sensor_center: 100.0
      lidar_timestamp_round: true
      lidar_timestamp_round_hz: 400.0

    # ODOMETRY OPTIONS ----
    odometry: STEAMLO
    odometry_options:
      debug_print: true
      debug_path: /home/asrl/ASRL/temp/steam_icp/boreas_velodyne/steamlo
      num_iters_icp: 10
      # init_num_frames: 0
      sample_voxel_size: 1.70
      # min_number_neighbors: 3
      min_distance_points: 0.1
      max_num_points_in_voxel: 18
      min_number_neighbors: 18
      max_number_neighbors: 18

      elastic:
        num_threads: 20

      steam:
        qc_diag: [50.0, 50.0, 50.0, 5.0, 5.0, 5.0]

        p0_pose: [1.0e-4, 1.0e-4, 1.0e-4, 1.0e-4, 1.0e-4, 1.0e-4]
        p0_vel: [1.0e-1, 1.0e-1, 1.0e-1, 1.0e-4, 1.0e-4, 1.0e-4]

        num_threads: 16
        r_imu_ang: [5.48885234e-06, 2.38789649e-05, 3.34471102e-06]
        q_bias_gyro: 1.0e-4
        p0_bias_gyro: 1.0e-2
        use_imu: false
        max_iterations: 5
        verbose: true
        delay_adding_points: 1
        p2p_loss_func: L2
        num_extra_states: 0
        filter_lifetimes: true
