/**:
  ros__parameters:
    log_dir: /home/ywu/ASRL/temp/steam_icp/kitti_raw/steam
    output_dir: /home/ywu/ASRL/temp/steam_icp/kitti_raw/steam

    # VISUALIZATION OPTIONS ----
    visualization_options:
      odometry: false
      raw_points: false
      sampled_points: false
      map_points: false
      T_sr_vec: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    # DATASET OPTIONS ----
    dataset: KITTI_raw
    dataset_options:
      all_sequences: true
      root_path: /home/ywu/ASRL/steam_icp/data/kitti_raw
      sequence: "00"
      init_frame: 0
      last_frame: 100000
      min_dist_lidar_center: 5.0
      max_dist_lidar_center: 100.0

    # ODOMETRY OPTIONS ----
    odometry: STEAM
    odometry_options:
      debug_print: true
      debug_path: /home/ywu/ASRL/temp/steam_icp/kitti_raw/steam

      elastic:
        num_threads: 20

      steam:
        T_sr_vec: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        qc_diag: [50.0, 50.0, 50.0, 5.0, 5.0, 5.0]
        use_rv: false
        num_threads: 20
