/**:
  ros__parameters:
    log_dir: /home/yuchen/ASRL/temp/steam_icp/kitti_raw/elastic
    output_dir: /home/yuchen/ASRL/temp/steam_icp/kitti_raw/elastic

    # VISUALIZATION OPTIONS ----
    visualization_options:
      odometry: false
      raw_points: false
      sampled_points: false
      map_points: false

    # DATASET OPTIONS ----
    dataset: KITTI_raw
    dataset_options:
      all_sequences: true
      root_path: /home/yuchen/ASRL/data/kitti_raw
      sequence: "00"
      init_frame: 0
      last_frame: 100000
      min_dist_lidar_center: 5.0
      max_dist_lidar_center: 100.0

    # ODOMETRY OPTIONS ----
    odometry: Elastic
    odometry_options:
      debug_print: true
      debug_path: /home/yuchen/ASRL/temp/steam_icp/kitti_raw/elastic

      elastic:
        num_threads: 10
