/**:
  ros__parameters:
    log_dir: /home/krb/ASRL/temp/steam_icp/kitti_raw/steamlio
    output_dir: /home/krb/ASRL/temp/steam_icp/kitti_raw/steamlio
    eval_only: false

    # VISUALIZATION OPTIONS ----
    visualization_options:
      odometry: true
      raw_points: false
      sampled_points: true
      map_points: false
      T_sr_vec: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    # DATASET OPTIONS ----
    dataset: KITTI_raw
    dataset_options:
      all_sequences: true
      root_path: /workspace/raid/krb/kitti-raw
      sequence: "06"
      init_frame: 0
      last_frame: 10000
      min_dist_sensor_center: 5.0
      max_dist_sensor_center: 100.0
      lidar_timestamp_round: true
      lidar_timestamp_round_hz: 3000.0

    # ODOMETRY OPTIONS ----
    odometry: STEAMLIO
    odometry_options:
      debug_print: true
      debug_path: /home/krb/ASRL/temp/steam_icp/kitti_raw/steamlio
      num_iters_icp: 10
      # sample_voxel_size: 1.50
      # min_distance_points: 0.1
      # max_num_points_in_voxel: 20
      # min_number_neighbors: 20
      # max_number_neighbors: 20

      elastic:
        num_threads: 20

      steam:
        T_sr_vec: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        qc_diag: [50000.0, 50000.0, 50000.0, 5000.0, 5000.0, 5000.0]
        use_rv: false
        num_threads: 16
        p0_pose: [1.0e-4, 1.0e-4, 1.0e-4, 1.0e-4, 1.0e-4, 1.0e-4]
        p0_vel: [1.0e-0, 1.0e-0, 1.0e-0, 1.0e-0, 1.0e-0, 1.0e-0]
        p0_accel: [1.0e-0, 1.0e-0, 1.0e-0, 1.0e-0, 1.0e-0, 1.0e-0]
        use_imu: false
        max_iterations: 5
        verbose: true
        delay_adding_points: 1
        p2p_loss_func: L2
        num_extra_states: 0
