/**:
  ros__parameters:
    log_dir: /home/krb/ASRL/temp/steam_icp/newer_college_dataset/steamlo
    output_dir: /home/krb/ASRL/temp/steam_icp/newer_college_dataset/steamlo
    eval_only: false

    # VISUALIZATION OPTIONS ----
    visualization_options:
      odometry: true
      raw_points: false
      sampled_points: true
      map_points: false

    # DATASET OPTIONS ----
    dataset: NewerCollege
    dataset_options:
      all_sequences: false
      root_path: /workspace/raid/krb/newer_college_dataset
      sequence: "01_short_experiment" #"boreas-2021-09-02-11-42"
      init_frame: 0 # 5675 (highway 7 front image)
      last_frame: 100000 # 5680 (highway 7 front image)
      min_dist_sensor_center: 0.1
      max_dist_sensor_center: 100.0
      lidar_timestamp_round: false
      lidar_timestamp_round_hz: 5000.0

    # ODOMETRY OPTIONS ----
    odometry: STEAMLO
    odometry_options:
      debug_print: true
      debug_path: /home/krb/ASRL/temp/steam_icp/newer_college_dataset/steamlo
      num_iters_icp: 10
      # init_voxel_size: 0.5
      # voxel_size: 0.5
      # init_sample_voxel_size: 0.5
      # sample_voxel_size: 0.5
      sample_voxel_size: 1.0
      min_number_neighbors: 10
      # max_number_neighbors: 25
      # voxel_lifetime: 100
      # map:
      # min_distance_points: 0.05
      # max_num_points_in_voxel: 100
      max_distance: 400.0  #LIO: 400
      # voxel_lifetime: 10
      min_number_keypoints: 0

      elastic:
        num_threads: 20

      steam:
        p2p_max_dist: 1.0
        # sim:
        ad_diag: [0.0, 0.0, 0.0, 100., 100., 100.]
        qc_diag: [50.0, 50.0, 50.0, 5.0, 5.0, 5.0]  #[50.0, 50.0, 50.0, 5.0, 5.0, 5.0] [12.5,12.5,12.5,1.25,1.25,1.25] # LO: 
        # qc_diag: [500.0, 500.0, 500.0, 50.0, 50.0, 50.0]  # LIO: qc_diag: [500.0, 500.0, 500.0, 50.0, 50.0, 50.0] 

        p0_pose: [1.0e-4, 1.0e-4, 1.0e-4, 1.0e-4, 1.0e-4, 1.0e-4]
        p0_vel: [1.0e-0, 1.0e-0, 1.0e-0, 1.0e-0, 1.0e-0, 1.0e-0]
        p0_accel: [1.0e-0, 1.0e-0, 1.0e-0, 1.0e-0, 1.0e-0, 1.0e-0]
        # ****************
        p2p_loss_func: L2
        num_extra_states: 0

        # qc_diag: [50.0,50.0,50.0,5.0,5.0,5.0]
        # ad_diag: [0.0,0.0,0.0,10.0,10.0,10.0]
        num_threads: 16
        
        # r_imu_acc: [0.43000461, 0.33698219, 0.29589244]
        # r_imu_ang: [0.04898588, 0.06860401, 0.04319808]
        # r_imu_acc: [0.03418968, 0.01292128, 0.00767178]
        # r_imu_ang: [5.75866815e-06, 2.21540004e-05, 3.48544315e-06]
        # r_imu_acc: [0.00156, 0.00156, 0.00156]
        
        # q_bias_accel: [1.0e-11, 4.0e-3, 1.0e-3]
        # q_bias_accel: [1.1236e-4, 1.1236e-4, 1.1236e-4]
        # p0_bias_accel: [1.0e-2, 1.0e-2, 1.0e-2]
        r_imu_ang: [4.326e-03, 4.326e-03, 4.326e-03]
        q_bias_gyro: 1.6e-4
        p0_bias_gyro: 1.0e-2
        use_imu: false
        use_accel: false
        max_iterations: 5
        verbose: true
        delay_adding_points: 1
        
        pk_bias_accel: 1.0e-1  # prior after init
        pk_bias_gyro: 1.0e-1  # prior after init
        xi_ig: [0., 0., 0., -1.51869911e-02,  3.07697005e-02, 0.]  # sim: [0., 0., 0., -0.0197052, 0.0285345, 0.] 
        
        gyro_loss_func: L2
        gyro_loss_sigma: 1.0
        T_sr_vec: [ 0.01849613,  0.00982219, -0.028535  ,  0.        ,  0.        , 3.14159265]
        # T_sr_vec: [ 0.,  0., 0.  ,  0.        ,  0.        , 0.]
        r_imu_acc: [5.0e-02, 5.0e-02, 5.0e-02]
        q_bias_accel: [1.1236e-1, 1.1236e-1, 1.1236e-1]
        p0_bias_accel: [1.0e-3, 1.0e-3, 1.0e-3]
        qg_diag: [1.0e-6, 1.0e-6, 1.0e-6, 1.0e-7, 1.0e-7, 1.0e-6]  # motion model for T_mi
        T_mi_init_only: true
        T_mi_init_cov: [1.0e-2, 1.0e-2, 1.0e-2, 1.0e-2, 1.0e-2, 1.0e-2]
        T_mi_prior_cov: [1.0e-2, 1.0e-2, 1.0e-3, 1.0, 1.0, 1.0e-4]
        acc_loss_func: L2
        acc_loss_sigma: 1.0
        gravity: -9.81599  #-9.8042
        filter_lifetimes: false  #LIO: false
        use_elastic_initialization: false  #LIO: false
        break_icp_early: true
        # keyframe_translation_threshold_m: 0.5
        # keyframe_rotation_threshold_deg: 15.0
        use_line_search: false
        use_pointtopoint_factors: false