/**:
  ros__parameters:
    log_dir: /home/krb/ASRL/temp/steam_icp/newer_college_dataset/steamlocv
    output_dir: /home/krb/ASRL/temp/steam_icp/newer_college_dataset/steamlocv
    eval_only: false

    # VISUALIZATION OPTIONS ----
    visualization_options:
      odometry: true
      raw_points: false
      sampled_points: true
      map_points: false

    # DATASET OPTIONS ----
    dataset: NewerCollege
    dataset_options:
      all_sequences: true
      root_path: /workspace/raid/krb/newer_college_dataset
      sequence: "05_quad_with_dynamics" #"boreas-2021-09-02-11-42"
      init_frame: 0 # 5675 (highway 7 front image)
      last_frame: 100000 # 5680 (highway 7 front image)
      min_dist_sensor_center: 0.1
      max_dist_sensor_center: 100.0
      lidar_timestamp_round: false
      lidar_timestamp_round_hz: 5000.0

    # ODOMETRY OPTIONS ----
    odometry: STEAMLOCV
    odometry_options:
      debug_print: true
      debug_path: /home/krb/ASRL/temp/steam_icp/newer_college_dataset/steamlocv
      num_iters_icp: 20
      threshold_orientation_norm: 0.1
      threshold_translation_norm: 0.025
      voxel_size: 0.25
      sample_voxel_size: 0.5 # 0.25
      size_voxel_map: 0.5
      min_number_neighbors: 10
      max_distance: 400.0  #LIO: 400

      steam:
        p2p_max_dist: 1.0
        p2p_loss_func: L2
        num_threads: 16
        max_iterations: 10
        verbose: true
        delay_adding_points: 1
        filter_lifetimes: false  #LIO: false
        break_icp_early: true
        use_line_search: false
        keyframe_translation_threshold_m: 0.0
        keyframe_rotation_threshold_deg: 0.0
        T_sr_vec: [ 0.01849613,  0.00982219, -0.028535  ,  0.        ,  0.        , 3.14159265]