/**:
  ros__parameters:
    log_dir: /home/asrl/ASRL/temp/steam_icp/simulation
    output_dir: /workspace/data1/simulation/
    root_path: /workspace/data1/
    sequence: "boreas-2021-09-02-11-42"
    lidar_config: "/home/asrl/Documents/steam_icp/steam_icp/simulation/vls128_config.txt"
    num_threads: 20
    verbose: false
    imu_rate: 200.0
    offset_imu: 0.0025
    min_dist_sensor_center: 0.1
    max_dist_sensor_center: 200.0
    noisy_measurements: true
    sim_length: 5.0
    lidar_range_std: 0.02
    r_accel: [0.195, 0.195, 0.195]
    r_gyro: [0.01, 0.01, 0.01]
    gravity: -9.8042
    p0_bias: 0.01
    q_bias: 0.01
    qc_diag: [6.18047567e+04, 6.18047567e+04, 3.40402641e+03, 6.13821100e+01, 6.13821100e+01, 9.85316597e+03]
    ad_diag: [100.11439693, 100.11512779, 100.08909343, 100.07804446, 100.07103628, 100.11791258]
    x0: [0., 0., -2., 0., 0., 0., 0., 0., 0., 0., 0., 0., -2.0, 0., 0., 0., 0., -1.0]
    accel_ramp_time: 0.3
    # x0: [0., 0., -2., 0., 0., 0., 0., 0., 0., 0., 0., 0., -0.5, 0., 0., 0., 0., -0.1]
    # x0: [0., 0., -2., -0.0197052, 0.0285345, 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.05.]
    walls: [-50., 50., -50., 50., 0., 10.]  # xmin, xmax, ymin, ymax, zmin, zmax
    sleep_delay: 0.0
    v_freqs : [2.7, 2.7, 2.7, 2.7, 2.7, 2.7]
    v_amps : [5.0, 8.0, 8.0, 1.5, 1.5, 3.5]
    ax: 3.0